// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rollout.Infrastructure.Persistence;

#nullable disable

namespace Rollout.Infrastructure.Migrations
{
    [DbContext(typeof(RolloutDbContext))]
    [Migration("20260412210857_AddTargetingRulesJson")]
    partial class AddTargetingRulesJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Rollout.Domain.Entities.FeatureFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RolloutPercentage")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("FeatureFlags", (string)null);
                });

            modelBuilder.Entity("Rollout.Domain.Entities.FeatureFlag", b =>
                {
                    b.OwnsMany("Rollout.Domain.Entities.TargetingRule", "TargetingRules", b1 =>
                        {
                            b1.Property<Guid>("FeatureFlagId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Attribute")
                                .IsRequired()
                                .HasMaxLength(100);

                            b1.Property<string>("Operator")
                                .IsRequired()
                                .HasMaxLength(50);

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(500);

                            b1.HasKey("FeatureFlagId", "__synthesizedOrdinal");

                            b1.ToTable("FeatureFlags");

                            b1
                                .ToJson("TargetingRules")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("FeatureFlagId");
                        });

                    b.Navigation("TargetingRules");
                });
#pragma warning restore 612, 618
        }
    }
}
